apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - agent-config.yaml
  - secret-delivery.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - cilium-egress-policy.yaml
