apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-agent
  namespace: bob
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-agent-secret-delivery
  namespace: bob
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-nango
  namespace: bob
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-nango-secret-delivery
  namespace: bob
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-backup
  namespace: bob
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-backup-secret-delivery
  namespace: bob
automountServiceAccountToken: false
