apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-agent
  namespace: bob
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-agent-secret-delivery
  namespace: bob
automountServiceAccountToken: false
