#cloud-config

hostname: bob-coolify
manage_etc_hosts: false
timezone: Europe/Stockholm

disable_root: false
ssh_pwauth: false
ssh_deletekeys: true
ssh_genkeytypes: [ed25519]
ssh_import_id:
  - gh:arek-e

package_update: true
package_upgrade: false
packages:
  - qemu-guest-agent

write_files:
  - path: /etc/hosts
    owner: root:root
    permissions: "0644"
    content: |
      127.0.0.1 localhost
      127.0.1.1 bob-coolify
      10.0.2.100 vault.lamb-bicolor.ts.net vault
      10.0.2.101 otel.lamb-bicolor.ts.net otel
      ::1 localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters

growpart:
  mode: auto
  devices: [/]

resize_rootfs: true

runcmd:
  - [systemctl, enable, --now, qemu-guest-agent]

final_message: "Bob Coolify VM is ready after $UPTIME seconds"
