apiVersion: v1
kind: Service
metadata:
  name: bob-agent
  namespace: bob
spec:
  selector:
    app.kubernetes.io/name: bob-agent
  ports:
    - name: http
      port: 8787
      targetPort: http
  type: ClusterIP
