apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: bob-agent.invalid/repository
    newName: ghcr.io/arek-e/bob-agent
    digest: sha256:798169376b882c33bbf1dac6e39d69b15a107bf4e1933bd7e9fedc0be5911ffb
  - name: cloudflared.invalid/repository
    newName: docker.io/cloudflare/cloudflared
    digest: sha256:e39ee8da81ad5e05d77f38d2f51c60ca51bf2a8450ac3abab50c17fdb91d91bf
  - name: bob-backup.invalid/repository
    newName: ghcr.io/arek-e/bob-data-backup
    digest: sha256:f80f3e772036910bdc9676a3e86270dc21c87ef7c361b48f61029f5063c75dfd
  - name: nango.invalid/repository
    newName: docker.io/nangohq/nango-server
    digest: sha256:a52964a41b5ff5d113e45d8ae76a6ffeb2b76ed6e147bc5078288d0f0c79f0c6
  - name: nango-postgres.invalid/repository
    newName: docker.io/library/postgres
    digest: sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777
  - name: nango-redis.invalid/repository
    newName: docker.io/library/redis
    digest: sha256:05a97a479bc73de66f087dc05b569010772880f778cc8671fa6b8aadee32e5c6
patches:
  - target:
      kind: ConfigMap
      name: bob-agent-bootstrap
    patch: |-
      - op: replace
        path: /data/BAO_ADDR
        value: http://openbao.openbao.svc.cluster.local:8200
      - op: replace
        path: /data/BOB_RELEASE_SHA
        value: 943122f3d2e539567b066b3d6412f1bcb0d4fdbc
      - op: replace
        path: /data/OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://prod-otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318
  - target:
      kind: ConfigMap
      name: bob-nango
    patch: |-
      - op: replace
        path: /data/NANGO_SERVER_URL
        value: https://nango.tpops.dev
      - op: replace
        path: /data/NANGO_PUBLIC_SERVER_URL
        value: https://nango.tpops.dev
      - op: replace
        path: /data/NANGO_PUBLIC_CONNECT_URL
        value: https://nango-connect.tpops.dev
replacements:
  - source:
      kind: ConfigMap
      name: bob-agent-bootstrap
      fieldPath: data.BAO_ADDR
    targets:
      - select:
          group: external-secrets.io
          version: v1
          kind: SecretStore
          name: bob-openbao
        fieldPaths:
          - spec.provider.vault.server
      - select:
          group: external-secrets.io
          version: v1
          kind: SecretStore
          name: bob-backup-openbao
        fieldPaths:
          - spec.provider.vault.server
      - select:
          group: external-secrets.io
          version: v1
          kind: SecretStore
          name: bob-nango-openbao
        fieldPaths:
          - spec.provider.vault.server
