apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository-service-account.yaml
  - repository-secret-store.yaml
  - repository-external-secret.yaml
  - project.yaml
  - application.yaml
