apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bob-repository
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bob-argocd-repository
    kind: SecretStore
  target:
    name: bob-repository
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: git
        url: git@github.com:arek-e/bob.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: apps/prod/bob/argocd/repository
        property: SSH_PRIVATE_KEY
