apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bob-argocd-repository
  namespace: argocd
spec:
  provider:
    vault:
      server: http://openbao.openbao.svc.cluster.local:8200
      path: ops
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: bob-argocd-repository
          serviceAccountRef:
            name: bob-argocd-repository
            audiences: [openbao]
